echo "# Copyright (c) 1993-2009 Microsoft Corp." > C:\Windows\System32\drivers\etc\Hosts
echo "#" >> C:\Windows\System32\drivers\etc\Hosts
echo "# This is a sample HOSTS file used by Microsoft TCP/IP for Windows. " >> C:\Windows\System32\drivers\etc\Hosts
echo "# " >> C:\Windows\System32\drivers\etc\Hosts
echo "# This file contains the mappings of IP addresses to host names. Each " >> C:\Windows\System32\drivers\etc\Hosts
echo "# entry should be kept on an individual line. The IP address should " >> C:\Windows\System32\drivers\etc\Hosts
echo "# be placed in the first column followed by the corresponding host name. " >> C:\Windows\System32\drivers\etc\Hosts
echo "# The IP address and the host name should be separated by at least one " >> C:\Windows\System32\drivers\etc\Hosts
echo "# space. " >> C:\Windows\System32\drivers\etc\Hosts
echo "# " >> C:\Windows\System32\drivers\etc\Hosts
echo "# Additionally, comments (such as these) may be inserted on individual " >> C:\Windows\System32\drivers\etc\Hosts
echo "# lines or following the machine name denoted by a '#' symbol. " >> C:\Windows\System32\drivers\etc\Hosts
echo "# " >> C:\Windows\System32\drivers\etc\Hosts
echo "# For example: " >> C:\Windows\System32\drivers\etc\Hosts
echo "# " >> C:\Windows\System32\drivers\etc\Hosts
echo "#      102.54.94.97     rhino.acme.com          # source server " >> C:\Windows\System32\drivers\etc\Hosts
echo "#       38.25.63.10     x.acme.com              # x client host " >> C:\Windows\System32\drivers\etc\Hosts
echo " " >> C:\Windows\System32\drivers\etc\Hosts
echo "# localhost name resolution is handled within DNS itself. " >> C:\Windows\System32\drivers\etc\Hosts
echo "#	127.0.0.1       localhost" >> C:\Windows\System32\drivers\etc\Hosts
echo "#	::1             localhost" > C:\Windows\System32\drivers\etc\Hosts " >> C:\Windows\System32\drivers\etc\Hosts

netsh advfirewall firewall Delete rule name="AdobeRule1" 
netsh advfirewall firewall Delete rule name="AdobeRule2" 
netsh advfirewall firewall Delete rule name="AdobeRule3" 
netsh advfirewall firewall Delete rule name="AdobeRule4" 
netsh advfirewall firewall Delete rule name="AdobeRule5" 
netsh advfirewall firewall Delete rule name="AdobeRule6" 
netsh advfirewall firewall Delete rule name="AdobeRule7" 
netsh advfirewall firewall Delete rule name="AdobeRule8" 
netsh advfirewall firewall Delete rule name="AdobeRule9" 
netsh advfirewall firewall Delete rule name="AdobeRule10" 
netsh advfirewall firewall Delete rule name="AdobeRule11" 
netsh advfirewall firewall Delete rule name="AdobeRule12" 
netsh advfirewall firewall Delete rule name="AdobeRule13" 
netsh advfirewall firewall Delete rule name="AdobeRule14" 
netsh advfirewall firewall Delete rule name="AdobeRule15" 
netsh advfirewall firewall Delete rule name="AdobeRule16" 
netsh advfirewall firewall Delete rule name="AdobeRule17" 
netsh advfirewall firewall Delete rule name="AdobeRule18" 
netsh advfirewall firewall Delete rule name="AdobeRule19" 
netsh advfirewall firewall Delete rule name="AdobeRule20" 
netsh advfirewall firewall Delete rule name="AdobeRule21" 
netsh advfirewall firewall Delete rule name="AdobeRule22" 
netsh advfirewall firewall Delete rule name="AdobeRule23" 
netsh advfirewall firewall Delete rule name="AdobeRule24" 
netsh advfirewall firewall Delete rule name="AdobeRule25" 
netsh advfirewall firewall Delete rule name="AdobeRule26" 
netsh advfirewall firewall Delete rule name="AdobeRule27" 
netsh advfirewall firewall Delete rule name="AdobeRule28" 
netsh advfirewall firewall Delete rule name="AdobeRule29" 
netsh advfirewall firewall Delete rule name="AdobeRule30" 
netsh advfirewall firewall Delete rule name="AdobeRule31" 
netsh advfirewall firewall Delete rule name="AdobeRule32" 
netsh advfirewall firewall Delete rule name="AdobeRule33" 
netsh advfirewall firewall Delete rule name="AdobeRule34" 
netsh advfirewall firewall Delete rule name="AdobeRule35" 
netsh advfirewall firewall Delete rule name="AdobeRule36" 
netsh advfirewall firewall Delete rule name="AdobeRule37" 
netsh advfirewall firewall Delete rule name="AdobeRule38" 
netsh advfirewall firewall Delete rule name="AdobeRule39" 
netsh advfirewall firewall Delete rule name="AdobeRule41" 
netsh advfirewall firewall Delete rule name="AdobeRule42" 
netsh advfirewall firewall Delete rule name="AdobeRule43" 
netsh advfirewall firewall Delete rule name="AdobeRule44" 
netsh advfirewall firewall Delete rule name="AdobeRule45" 
netsh advfirewall firewall Delete rule name="AdobeRule46" 
netsh advfirewall firewall Delete rule name="AdobeRule47" 
netsh advfirewall firewall Delete rule name="AdobeRule48" 
netsh advfirewall firewall Delete rule name="AdobeRule49" 
netsh advfirewall firewall Delete rule name="AdobeRule50" 
netsh advfirewall firewall Delete rule name="AdobeRule51" 
netsh advfirewall firewall Delete rule name="AdobeRule52" 
netsh advfirewall firewall Delete rule name="AdobeRule53" 
netsh advfirewall firewall Delete rule name="AdobeRule54" 
netsh advfirewall firewall Delete rule name="AdobeRule55" 
netsh advfirewall firewall Delete rule name="AdobeRule56" 
netsh advfirewall firewall Delete rule name="AdobeRule57" 
netsh advfirewall firewall Delete rule name="AdobeRule58" 
netsh advfirewall firewall Delete rule name="AdobeRule59" 
netsh advfirewall firewall Delete rule name="AdobeRule60" 
netsh advfirewall firewall Delete rule name="AdobeRule61" 
netsh advfirewall firewall Delete rule name="AdobeRule62" 
netsh advfirewall firewall Delete rule name="AdobeRule63" 
netsh advfirewall firewall Delete rule name="AdobeRule64" 
netsh advfirewall firewall Delete rule name="AdobeRule65" 
netsh advfirewall firewall Delete rule name="AdobeRule66" 
netsh advfirewall firewall Delete rule name="AdobeRule67" 
netsh advfirewall firewall Delete rule name="AdobeRule68" 
netsh advfirewall firewall Delete rule name="AdobeRule69" 
netsh advfirewall firewall Delete rule name="AdobeRule70" 
netsh advfirewall firewall Delete rule name="AdobeRule71" 
netsh advfirewall firewall Delete rule name="AdobeRule72" 
netsh advfirewall firewall Delete rule name="AdobeRule73" 
netsh advfirewall firewall Delete rule name="AdobeRule74" 
netsh advfirewall firewall Delete rule name="AdobeRule75" 
netsh advfirewall firewall Delete rule name="AdobeRule76" 
netsh advfirewall firewall Delete rule name="AdobeRule77" 
netsh advfirewall firewall Delete rule name="AdobeRule78" 
netsh advfirewall firewall Delete rule name="AdobeRule79" 
netsh advfirewall firewall Delete rule name="AdobeRule80" 
netsh advfirewall firewall Delete rule name="AdobeRule81" 
netsh advfirewall firewall Delete rule name="AdobeRule82" 
netsh advfirewall firewall Delete rule name="AdobeRule83" 
netsh advfirewall firewall Delete rule name="AdobeRule84" 
netsh advfirewall firewall Delete rule name="AdobeRule85" 
netsh advfirewall firewall Delete rule name="AdobeRule86" 
netsh advfirewall firewall Delete rule name="AdobeRule87" 
netsh advfirewall firewall Delete rule name="AdobeRule88" 
netsh advfirewall firewall Delete rule name="AdobeRule89" 
netsh advfirewall firewall Delete rule name="AdobeRule90" 
netsh advfirewall firewall Delete rule name="AdobeRule91" 
netsh advfirewall firewall Delete rule name="AdobeRule92" 
netsh advfirewall firewall Delete rule name="AdobeRule93" 
netsh advfirewall firewall Delete rule name="AdobeRule94" 
netsh advfirewall firewall Delete rule name="AdobeRule95" 
netsh advfirewall firewall Delete rule name="AdobeRule96" 
netsh advfirewall firewall Delete rule name="AdobeRule97" 
netsh advfirewall firewall Delete rule name="AdobeRule98" 
netsh advfirewall firewall Delete rule name="AdobeRule99" 
netsh advfirewall firewall Delete rule name="AdobeRule100"
netsh advfirewall firewall Delete rule name="AdobeRule101"
netsh advfirewall firewall Delete rule name="AdobeRule102"
netsh advfirewall firewall Delete rule name="AdobeRule103"
netsh advfirewall firewall Delete rule name="AdobeRule104"
netsh advfirewall firewall Delete rule name="AdobeRule105"
netsh advfirewall firewall Delete rule name="AdobeRule106"
netsh advfirewall firewall Delete rule name="AdobeRule107"
netsh advfirewall firewall Delete rule name="AdobeRule108"
netsh advfirewall firewall Delete rule name="AdobeRule109"
netsh advfirewall firewall Delete rule name="AdobeRule110"
netsh advfirewall firewall Delete rule name="AdobeRule111"
netsh advfirewall firewall Delete rule name="AdobeRule112"
netsh advfirewall firewall Delete rule name="AdobeRule113"
netsh advfirewall firewall Delete rule name="AdobeRule114"
netsh advfirewall firewall Delete rule name="AdobeRule115"
netsh advfirewall firewall Delete rule name="AdobeRule116"
netsh advfirewall firewall Delete rule name="AdobeRule117"
netsh advfirewall firewall Delete rule name="AdobeRule118"
netsh advfirewall firewall Delete rule name="AdobeRule119"
netsh advfirewall firewall Delete rule name="AdobeRule120"
netsh advfirewall firewall Delete rule name="AdobeRule121"
netsh advfirewall firewall Delete rule name="AdobeRule122"
netsh advfirewall firewall Delete rule name="AdobeRule123"
netsh advfirewall firewall Delete rule name="AdobeRule124"
netsh advfirewall firewall Delete rule name="AdobeRule125"
netsh advfirewall firewall Delete rule name="AdobeRule126"
netsh advfirewall firewall Delete rule name="AdobeRule127"
netsh advfirewall firewall Delete rule name="AdobeRule128"
netsh advfirewall firewall Delete rule name="AdobeRule129"
netsh advfirewall firewall Delete rule name="AdobeRule130"
netsh advfirewall firewall Delete rule name="AdobeRule131"
netsh advfirewall firewall Delete rule name="AdobeRule132"
netsh advfirewall firewall Delete rule name="AdobeRule133"
netsh advfirewall firewall Delete rule name="AdobeRule134"
netsh advfirewall firewall Delete rule name="AdobeRule135"
netsh advfirewall firewall Delete rule name="AdobeRule136"
netsh advfirewall firewall Delete rule name="AdobeRule137"
netsh advfirewall firewall Delete rule name="AdobeRule138"
netsh advfirewall firewall Delete rule name="AdobeRule139"
netsh advfirewall firewall Delete rule name="AdobeRule140"
netsh advfirewall firewall Delete rule name="AdobeRule141"
netsh advfirewall firewall Delete rule name="AdobeRule142"
netsh advfirewall firewall Delete rule name="AdobeRule143"
netsh advfirewall firewall Delete rule name="AdobeRule144"
netsh advfirewall firewall Delete rule name="AdobeRule145"
netsh advfirewall firewall Delete rule name="AdobeRule146"
netsh advfirewall firewall Delete rule name="AdobeRule147"
netsh advfirewall firewall Delete rule name="AdobeRule148"
netsh advfirewall firewall Delete rule name="AdobeRule149"
netsh advfirewall firewall Delete rule name="AdobeRule150"
netsh advfirewall firewall Delete rule name="AdobeRule151"
netsh advfirewall firewall Delete rule name="AdobeRule152"
netsh advfirewall firewall Delete rule name="AdobeRule153"
netsh advfirewall firewall Delete rule name="AdobeRule154"